# Generated by Django 2.2.6 on 2019-11-17 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0003_reviews_viewedproducts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='r_star',
            field=models.CharField(max_length=4),
        ),
    ]
