# Generated by Django 2.2.6 on 2019-11-17 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0004_auto_20191117_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viewedproducts',
            name='p_rating',
        ),
        migrations.AddField(
            model_name='viewedproducts',
            name='p_star',
            field=models.CharField(default='null', max_length=4),
        ),
    ]
