# Generated by Django 2.2.6 on 2019-11-17 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0005_auto_20191117_1249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viewedproducts',
            old_name='p_name',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='viewedproducts',
            old_name='p_url',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='viewedproducts',
            old_name='r_count',
            new_name='reviewcount',
        ),
        migrations.RenameField(
            model_name='viewedproducts',
            old_name='p_star',
            new_name='star',
        ),
        migrations.RenameField(
            model_name='viewedproducts',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AddField(
            model_name='viewedproducts',
            name='url',
            field=models.CharField(default='null', max_length=1000, unique=True),
        ),
    ]
