# Generated by Django 2.2.6 on 2019-11-18 11:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0009_auto_20191118_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='analyze_date',
            field=models.DateField(default='1990-10-10', verbose_name=datetime.datetime(2019, 11, 18, 15, 28, 52, 184295)),
        ),
    ]
