# Generated by Django 2.2.6 on 2019-11-18 11:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0011_auto_20191118_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='isFake',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='analyze_date',
            field=models.DateField(default='1990-10-10', verbose_name=datetime.datetime(2019, 11, 18, 15, 43, 15, 166147)),
        ),
    ]
