# Generated by Django 2.2.6 on 2019-11-18 11:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0012_auto_20191118_1543'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='user',
            new_name='p_user',
        ),
        migrations.AlterField(
            model_name='product',
            name='analyze_date',
            field=models.DateField(default='1990-10-10', verbose_name=datetime.datetime(2019, 11, 18, 15, 44, 36, 125683)),
        ),
    ]
